global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'petbuddy-monitor'

scrape_configs:
  - job_name: 'interaction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['interaction-service:8084']
        labels:
          service: 'interaction-service'
          environment: 'development'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

